### ISSUE TITLE
No admin user for ecko(mastodon fork) application

### ISSUE THREAD

**Issue by pydah** [YunoHost-Apps/ecko_ynh#31]
### Describe the bug
After ecko app installation, I can create just ordinary user, so I can't manage admin activities such writing policy instance or upload logo instance.

### Context
- Hardware: *VPS bought online - Debian 10
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- If upgrading, current package version: 2022.02.03~ynh1

### Steps to reproduce
WebAdmin Home Page --> Application --> search ecko app --> click Install
WebAdmin Home Page --> User --> New User
WebAdmin Home Page --> User --> Manage Groups and permission --> Add permission to all user to mastodon application 

NOTE: There is no admin permission to add to groups or to users

### Expected behavior
Log in in to the mastodon instance, edit profile and see admin setting

**Comment by weex** [comment]
The installation should create an admin account with the username and email of the YNH user you selected. Did that account not work or are you asking how to create other admin accounts?

**Comment by pydah** [comment]
Sorry, I didn't realize that you mentioned, tath an admin user had been created as you explained. I can enter with an admin user now. Sorry if i opened an issue related to a false problem. Anyway, I can imagine that a new admin user is possibile via CLI, right?

**Comment by weex** [comment]
Hi pydah, I'm glad you created the issue because others may have the same question. Yes, you can modify any account into an admin using `tootctl` https://docs.joinmastodon.org/admin/tootctl/#accounts. We don't have more specific instructions for this on YunoHost installs but if you have trouble, reply and I'll type it up. Otherwise you can close this if the issue is resolved.

**Comment by pydah** [comment]
Thanks weex. I think I can close the issue, but before I try to recap what take me to open an issue:

1) I have installed yunohost on my machine
2) I have created a yunohost user, related to my domain
3) I have installed ecko application
4) I didn't realize that the user created to step 2), could be my admin user for ecko application

I proceed to close the issue.

Thanks,
pydah
