### ISSUE TITLE
Problem: Old data not been deleted (?)

### ISSUE THREAD

**Issue by jorgesat** [YunoHost-Apps/ecko_ynh#32]
### Describe the bug

It seems there is a bunch of data being accumulated and not deleted by cron jobs as it should be?

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH / webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

`ncdu` will show you how much disk space is used (10 GB in my case)
`df -h` shows that folder /dev/sda1 is using 110 GB. 
It is not clear where the extra 100 GB come from.

There are only few apps installed, being ecko the largest and most used one.

### Expected behavior

HD space used should be less.

**Comment by weex** [comment]
It's most likely the cached media which is taking up the space. I'm not sure immediately how to run it on YNH but the command that should work is `tootctl media remove`

Related: https://github.com/magicstone-dev/ecko/issues/383

**Comment by jorgesat** [comment]
I have more insights regarding this issue.

According to `/etc/cron.d/ecko`, the following tasks should be executed:

```
@daily cd /var/www/ecko/live && RAILS_ENV=production bin/tootctl media remove
@monthly cd /var/www/ecko/live && RAILS_ENV=production bin/tootctl media remove$
@monthly cd /var/www/ecko/live && RAILS_ENV=production bin/tootctl accounts cull
@monthly cd /var/www/ecko/live && RAILS_ENV=production bin/tootctl statuses rem$
@monthly cd /var/www/ecko/live && RAILS_ENV=production bin/tootctl preview_card$
```

However, when I try to execute `RAILS_ENV=production bin/tootctl media remove` in directory `/var/www/ecko/live`, the output is the following:
`/usr/bin/env: ‘ruby’: No such file or directory`

**Comment by weex** [comment]
That makes sense! YunoHost has a special way of invoking ruby for each installed application. If you check in the /scripts directory here you'll see what those look like. We'll have to figure out what those lines should look like and how to modify them for installation.

**Comment by jorgesat** [comment]
I could not locate the scripts. Could you please let me know a way to get rid of the cache in the meantime?

**Comment by weex** [comment]
The issue above is closest I've done to what's necessary. It's going to be something like this line: https://github.com/YunoHost-Apps/ecko_ynh/blob/master/scripts/install#L218

**Comment by weex** [comment]
Asked in the YNH dev chat and @tituspijean offered this to try:
Have a look at ynh_use_ruby's documentation in https://github.com/YunoHost-Apps/ecko_ynh/blob/master/scripts/ynh_install_ruby__2
Looks like if you use `__YNH_RUBY__` in a cron file deployed by ynh_add_config, it will replaced by the path towards ruby
