### ISSUE TITLE
Problem: Update not possible due to backup size

### ISSUE THREAD

**Issue by jorgesat** [YunoHost-Apps/ecko_ynh#35]
### Describe the bug
Cannot update because the size of the media folder is too large and there is no space left for ynh's backup previous to update.

### Context

- Hardware: *VPS bought online *
- YunoHost version: 4.3.6.3
- Ecko version: 2022.02.03~ynh1
- I have access to my server: *Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Expected behavior

The cron job should be able to remove old media. Otherwise, a way to remove it manually should be available.

**Comment by weex** [comment]
Manual removal will look something like https://github.com/YunoHost-Apps/ecko_ynh/blob/master/scripts/install#L218. When I get a chance to test it I'll give the exact command.

**Comment by jorgesat** [comment]
When trying to troubleshoot we realized toolctl is not installed.

**Comment by weex** [comment]
We use it to create the first admin account, so it's there, but resolving all the environment variables remains to be done. I'm also curious how other ynh apps handle cronjobs.

**Comment by jorgesat** [comment]
If I run ` ls /opt/rbenv/versions/ecko/bin/` there is no toolctl there. It would be great if you can find out a way to execute the delete manually.

**Comment by weex** [comment]
tootctl is in /var/www/ecko/live/bin but I tried putting together a script and running it as root, but I get this error:`/usr/bin/env: ‘ruby’: No such file or directory`.

FWIW, the crontab stuff seems like it may have been fixed in the latest version, but yes I'll keep trying to run tootctl manually.

**Comment by jorgesat** [comment]
I get the same error.
I have seen that it was fixed but YHN requires backing up the whole app prior to update and that is not working given the size of the media folder.

**Comment by jorgesat** [comment]
I have opted to delete the cache manually and managed to update. I guess the cron jobs will work in the new version. I am closing the issue.
